.TH "MainFunction.cpp" 3 "2022年 十一月 22日 星期二" "Version 1.0.0" "ContactAddressBook" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MainFunction.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'CContact\&.h'\fP
.br
\fC#include 'CContact\&.cpp'\fP
.br
\fC#include 'AddressBook\&.h'\fP
.br
\fC#include 'AddressBook\&.cpp'\fP
.br

.SS "类"

.in +1c
.ti -1c
.RI "class \fBMainFunction\fP"
.br
.RI "解释在 \fBmain\&.cpp\fP 中调用到的函数 Explanation of some functions used in \fBmain\&.cpp\fP "
.in -1c
.SH "作者"
.PP 
由 Doyxgen 通过分析 ContactAddressBook 的 源代码自动生成\&.
