.TH "test" 3 "2022年 十一月 24日 星期四" "Version 1.0.0" "ContactAddressBook" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test \- 测试列表 
.PP

.IP "\fB成员 \fBAddressBook::Add\fP (\fBCContact\fP &contact)\fP" 1c
  
.IP "\fB成员 \fBAddressBook::operator[]\fP (int indexOfContact)\fP" 1c
  
.IP "\fB成员 \fBAddressBook::Sort\fP ()\fP" 1c
  
.IP "\fB成员 \fBAddressBook::SortGroup\fP ()\fP" 1c
  
.IP "\fB成员 \fBCContact::operator<\fP (const \fBCContact\fP &) const\fP" 1c
 name = 'Frank', number = '1596', Group = 'Student'  
.IP "\fB成员 \fBmain\fP ()\fP" 1c
  
.IP "\fB成员 \fBMainFunction::DeleteCommand\fP (\fBAddressBook\fP &Book)\fP" 1c
  
.IP "\fB成员 \fBmatch\fP (std::string &pattern, std::string &source)\fP" 1c
  
.IP "\fB成员 \fBpr\fP (const \fBCContact\fP &lhsContact, const \fBCContact\fP &rhsContact)\fP" 1c
 
.PP

